// Generated by https://quicktype.io

import { OpenTripXid } from './open-trip-xid.model';

export interface OpenTripAutoSuggest {
  type: string;
  features: Feature[];
}

export interface Feature {
  xidInfo?: OpenTripXid;
  type: FeatureType;
  id: string;
  geometry: Geometry;
  properties: Properties;
}

export interface Geometry {
  type: GeometryType;
  coordinates: number[];
}

export enum GeometryType {
  Point = 'Point',
}

export interface Properties {
  xid: string;
  name: string;
  highlighted_name: string;
  dist: number;
  rate: number;
  osm?: string;
  kinds: string;
  wikidata?: string;
}

export enum FeatureType {
  Feature = 'Feature',
}
